# Change these first
owner: adaptivehealthintelligence # Your GitHub organization or username, where this repository lives
repo: site-monitoring # The name of this repository
assignees: garybrowne
projects:
    - name: Site Monitoring
      columns:
          - To do
          - In progress
          - Done
sites:
    - name: MFIT get pt API (DEV)
      url: $MFIT_GET_PT_API_DEV
    - name: MFIT get pt API (PROD)
      url: $MFIT_GET_PT_API_PROD
    - name: PlatinumC
      url: $PLATINUMC_MIDDLEWARE
    - name: AUTOMATIC
      url: $AUTOMATIC_MIDDLEWARE
    - name: COVID-I Dashboard
      url: $COVIDI_DASHBOARD
    - name: MotC Project
      url: $MOTC_PROJECT
    - name: MotC Navigator Portal
      url: $MOTC_NAVIGATOR_PORTAL
    - name: MFIT portal
      url: $MFIT
    - name: Adaptive Health Intelligence
      url: $AHI
    - name: BEAT-CF
      url: $BEAT_CF

status-website:
    # Add your custom domain name, or remove the `cname` line if you don't have a domain
    # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
    # cname: demo.upptime.js.org
    baseUrl: /site-monitoring
    logoUrl: https://adaptivehealthintelligence.org.au/wp-content/uploads/2019/09/Adaptive-Health-Intelligence-Logo-980x387.jpg
    name: AHI Site Monitoring
    introTitle: AHI Site Monitoring
    introMessage: Working together to create a better way for clinical research & healthcare
    navbar:
        - title: Status
          href: https://www.youtube.com/watch?v=oHg5SJYRHA0
    robotsText: "User-agent * \n Disallow: * /"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
